# Generated by Django 4.2.19 on 2025-05-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenease', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='gen',
            field=models.CharField(blank=True, default='desconeguda', max_length=255),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='malaltia',
            field=models.CharField(blank=True, default='desconeguda', max_length=255),
        ),
    ]
