# Generated by Django 4.2.19 on 2025-03-10 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phenapp', '0002_client_usuari_rename_missatge_message_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Usuari',
            new_name='Pacient',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AlterField(
            model_name='log',
            name='usuari',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='phenapp.clinic'),
        ),
    ]
