# Generated by Django 4.2.19 on 2025-04-02 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phenapp', '0004_clinic_is_active_clinic_is_staff_clinic_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacient',
            name='email',
        ),
        migrations.AddField(
            model_name='pacient',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='phenapp.clinic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacient',
            name='codi_pacient',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacient',
            name='cognom',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacient',
            name='dni',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacient',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculí'), ('F', 'Femení'), ('O', 'Altres')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pacient',
            name='nom',
            field=models.CharField(max_length=255),
        ),
    ]
