# Generated by Django 4.2.19 on 2025-04-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenapp', '0005_remove_pacient_email_pacient_clinic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='pacient',
            name='caracteristiques',
            field=models.ManyToManyField(blank=True, to='phenapp.feature'),
        ),
        migrations.AddField(
            model_name='pacient',
            name='malalties',
            field=models.ManyToManyField(blank=True, to='phenapp.disease'),
        ),
    ]
