# Generated by Django 4.2.19 on 2025-04-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenapp', '0006_disease_feature_pacient_caracteristiques_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='dni',
            field=models.CharField(max_length=20),
        ),
    ]
