# Generated by Django 4.2.19 on 2025-04-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenapp', '0007_alter_pacient_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='cognom',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='nom',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
