# Generated by Django 4.2.19 on 2025-04-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenapp', '0008_alter_pacient_cognom_alter_pacient_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='dni',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
