# Generated by Django 4.2.19 on 2025-04-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenapp', '0009_alter_pacient_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='codi',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
