# Generated by Django 4.2.19 on 2025-05-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenapp', '0010_alter_feature_codi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='gen',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pacient',
            name='malaltia',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
