# Generated by Django 4.2.19 on 2025-05-07 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phenapp', '0011_pacient_gen_pacient_malaltia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacient',
            name='cognom',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='malalties',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='nom',
        ),
    ]
