# Generated by Django 4.2.19 on 2025-05-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenapp', '0012_remove_pacient_cognom_remove_pacient_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='cognom',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pacient',
            name='dni',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pacient',
            name='malalties',
            field=models.ManyToManyField(blank=True, to='phenapp.disease'),
        ),
        migrations.AddField(
            model_name='pacient',
            name='nom',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
